# Generated by Django 5.0.2 on 2024-07-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatbot_conversation_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='description',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=10),
        ),
    ]
