# Generated by Django 5.0.2 on 2024-08-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatbot_description_conversation_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='chatbot',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Chatbot',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
