# Generated by Django 5.1 on 2024-10-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pdfdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdfDocument',
        ),
    ]
