# Generated by Django 5.1 on 2024-11-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_file_uploadedpdf_file_path_uploadedpdf_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedpdf',
            old_name='file_path',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='user',
        ),
    ]
