"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9a-yvz60=$57k19r*mmmi-5=-v2648r@^8qqq-&_=p188#lfui'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []





INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'corsheaders',
    'rest_framework_simplejwt',
    'django_extensions',
    # 'djstripe',
    'django.contrib.sites',
    'allauth',
    'allauth.account',

    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # Correct provider for Google
    'rest_framework.authtoken',  # Ensure this is after the comma

]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # add this line
    'corsheaders.middleware.CorsMiddleware',  # add this line
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'api.middleware.SomeCustomMiddleware',
    # 'api.middleware.YourMiddlewareClassName',
    'api.middleware.SomeCustomMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Add this line
     'corsheaders.middleware.CorsMiddleware',

    




]




# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'SCOPE': [
#             'profile',
#             'email',
#         ],
#         'AUTH_PARAMS': {
#             'access_type': 'online',
#         }
#     }
# }



# Google OAuth Credentials
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '719066176783-ls7e7hu7sdn0n5k4eg8khdcmn8nkgtjm.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'METHOD': 'oauth2',
    }
}


LOGIN_REDIRECT_URL = '/home'
SITE_ID = 1


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


from datetime import timedelta

# JWT settings (optional, you can customize these)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


ROOT_URLCONF = 'backend.urls'



import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

CORS_ALLOW_ALL_ORIGINS = True



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#          'OPTIONS': {
#             'timeout': 30,  # Increase the timeout to 20 seconds
#         }
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'new_db.sqlite3',  # Change to a new file name
        'OPTIONS': {
            'timeout': 60,
        }
    }
}

allow_reuse=True



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "api/static",  # Add your static files directory
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
]

CORS_ALLOWED_ORIGINS = [
    # 'http://localhost:3000',  # Frontend URL for development
    'https://your-frontend-domain.com',  # Production URL (if applicable)
    'https://1ea5-154-57-223-240.ngrok-free.app',  # Ngrok URL (if used)
    'https://c93c-119-73-112-226.ngrok-free.app',  # ngrok URL
    # 'http://192.168.1.8:3000',
    'https://e9d2-119-63-138-252.ngrok-free.app'

]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
]



import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




ALLOWED_HOSTS = ['localhost', '127.0.0.1', '918a-154-57-223-112.ngrok-free.app','http://192.168.1.8:3000']





APPEND_SLASH = False



import os
from dotenv import load_dotenv

load_dotenv()

# Access the Hugging Face API token
HF_TOKEN = os.getenv("HUGGINGFACEHUB_API_TOKEN")
if not HF_TOKEN:
    raise EnvironmentError("HUGGINGFACEHUB_API_TOKEN not found in environment variables")

os.environ["HUGGINGFACEHUB_API_TOKEN"] = HF_TOKEN


STRIPE_TEST_SECRET_KEY = 'sk_test_51PQQsWIJIsx7jmFZGSmKtlhhxQT0EkPhWcbVOiPHRtrOHfefIeQnQU5lM7vqVYqv99MCeKEizEvLhhTbbpzcyxjx00tLMFCtGG'



CSRF_COOKIE_SECURE = True  

STRIPE_TEST_PUBLIC_KEY = 'pk_test_51PQQsWIJIsx7jmFZxeK72wC321674plCOCLaslbW7gEDLUpnFLixxrLGqCp5v2ZBoZKLjURFd5WEhkPfdTAywsNi00mHhvQ8Tc'
STRIPE_TEST_SECRET_KEY = 'sk_test_51PQQsWIJIsx7jmFZGSmKtlhhxQT0EkPhWcbVOiPHRtrOHfefIeQnQU5lM7vqVYqv99MCeKEizEvLhhTbbpzcyxjx00tLMFCtGG'


# STRIPE_WEBHOOK_SECRET = ' whsec_ab85723abe43c96e5cb0edeb181480736f44920fe070abbe0e42921a39ded118'
STRIPE_WEBHOOK_SECRET = 'whsec_ab85723abe43c96e5cb0edeb181480736f44920fe070abbe0e42921a39ded118'


HUGGINGFACEHUB_API_TOKEN = "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"

STRIPE_SUCCESS_URL = 'http://localhost:3000/'
STRIPE_CANCEL_URL = 'http://localhost:3000/cancel'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'attareh542@gmail.com'
EMAIL_HOST_PASSWORD = 'olub mwyt zerw quub'
DEFAULT_FROM_EMAIL = 'attareh542@gmail.com'




SOCIAL_AUTH_GOOGLE_CLIENT_ID = "62964421677-krntlqgcfo4ec9ke71pn7qe4ui244ng5.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_CLIENT_SECRET = "your-client-secret"

AUTHENTICATION_BACKENDS = [
   
    'django.contrib.auth.backends.ModelBackend',  # Keep the default backend
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth

]




SITE_ID = 1  # Ensure this matches your Site framework setup

# Google provider settings
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '62964421677-krntlqgcfo4ec9ke71pn7qe4ui244ng5.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'